version: '3'

services:
  backend:
    build: .
    container_name: 'backend_container'
    ports:
      - 3001:3001
    depends_on:
      - database
    volumes:
      - ./:/usr/app/backend/

  database:
    image: mysql
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root